site_name: Meu blog que ninguém lê
site_description: "Um canto escuro da internet"
site_url: https://www.titulomutante.com.br
theme:
    name: material
    custom_dir: overrides
    palette:          
      primary: custon 
    favicon: assets/images/favicon.ico
    features:
        - content.code.copy
        - navigation.indexes
        - navigation.top
        - navigation.tabs
        - navigation.expand
        - navigation.path
        - toc.follow
        - toc.integrate
    icon:
        repo: material/git
    language: pt-BR
extra_css:
    - stylesheets/extra.css
extra_javascript:  
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
plugins:
    - blog:
        post_excerpt: optional
        post_excerpt_separator: <!--more-->
        blog_dir: .
        post_url_format: "blog/{slug}"
        archive_url_format: "blog/archive/{date}"
        categories_url_format: "category/{slug}"
        categories: true
        archive: false
    - search
    - rss:
          match_path: docs/posts/.*
          date_from_meta:
            as_creation: date
          categories:
            - categories
            - tags
          image:
              https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Feed-icon.svg/128px-Feed-icon.svg.png
    - tags:
          enabled: true          
extra:
    social:
        - icon: material/mastodon
          link: https://ursal.zone/@Kriptolix
          name: Diego on mastodon.social        
        - icon: material/github
          link: https://github.com/kriptolix
        - icon: material/rss
          link: https://www.titulomutante.com.br
copyright: Copyright &copy; 2025 Kriptolix
markdown_extensions:
    - tables
    - attr_list
    - footnotes
    - md_in_html
    - admonition  
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
        options:
          custom_icons:
            - overrides/.icons
    - pymdownx.highlight:
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.blocks.caption
    

nav:
  - Início: index.md  
  - Sob um Céu Estranho:     
    - monocerus/sob_um_ceu_estranho/inicio.md
    - monocerus/sob_um_ceu_estranho/basico.md
    - Nave:
      - monocerus/sob_um_ceu_estranho/nave/criando_a_nave.md
    - Personagens:
      - monocerus/sob_um_ceu_estranho/personagens/criação.md
      - monocerus/sob_um_ceu_estranho/personagens/arquetipos.md
      - monocerus/sob_um_ceu_estranho/personagens/aspectos.md
      - monocerus/sob_um_ceu_estranho/personagens/habilidades.md
      - monocerus/sob_um_ceu_estranho/personagens/passados.md
      - monocerus/sob_um_ceu_estranho/personagens/motivações.md
      - monocerus/sob_um_ceu_estranho/personagens/fraquezas.md
      - monocerus/sob_um_ceu_estranho/personagens/progressão.md
    - O Jogo:
      - monocerus/sob_um_ceu_estranho/jogo/desafios.md
      - monocerus/sob_um_ceu_estranho/jogo/ferramentas.md
      - monocerus/sob_um_ceu_estranho/jogo/equipamento.md
      - monocerus/sob_um_ceu_estranho/jogo/consequencias.md
    - Narrador:
      - monocerus/sob_um_ceu_estranho/narrador/antagonistas.md
      - monocerus/sob_um_ceu_estranho/narrador/contadores.md
    - Game Design:
      - monocerus/game_design/diario.md         
  - Sobre Esse Blog: page_about.md